spring:
  application:
    name: godeliver


  datasource:
    url: jdbc:postgresql://localhost:5432/godeliver
    username: godeliver
    password: godeliver_dev
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true